обработка дублирования при сохранении URL
dubrovsky1/url-shortener pull request #13
Opened 2024-02-03 23:21 UTC by dubrovsky1

2024-02-05 13:00 UTC, bambruysk requested changes
Нужно избавиться от ненужных фаталов. Также, если используете pgx - посмотреть в сторону pgx.Batch - он неплохо справляется

2024-02-05 13:00 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +		log.Fatal("Postgresql Save. Insert error. ", err)
Не надо тут фаталить, повалится весь сервер из-за банального сбоя в сети. например. Лучше вернуть ошибку

2024-02-05 13:00 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +		log.Fatal("Postgresql InsertBatch. Begin transaction error. ", err)
не надо фаталить, прост вернуть ошибку

2024-02-05 13:00 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +		log.Fatal("Postgresql InsertBatch. Prepare query insert error. ", err)
см выше

2024-02-05 13:00 UTC, bambruysk commented on cmd/shortener/main.go
> +}
лучше сделать это в пакете storage

2024-02-07 18:45 UTC, dubrovsky1 commented
Исправил замечания

2024-02-10 08:39 UTC, bambruysk requested changes
Нужно добить фаталы

2024-02-10 08:39 UTC, bambruysk commented on internal/storage/file/file.go
> +				log.Fatal("File InsertBatch. Insert error. ", err)
все еще фатал

2024-02-10 08:39 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +	}
фаталим только в мейне

2024-02-10 08:39 UTC, bambruysk commented on internal/storage/storage.go
> +		}
лучше вернуть ошибку и сфаталить в мейн

2024-02-10 13:34 UTC, dubrovsky1 commented
@bambruysk готово, оставил Fatal только в main

2024-02-13 07:07 UTC, bambruysk approved these changes
принято

2024-02-13 17:44 UTC, merged